apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pipeline-deploy
spec:
  selector:
    matchLabels:
      app: app-pipeline
  replicas: 3
  template:
    metadata:
      labels:
        app: app-pipeline
    spec:
      containers:
        - name: app-pipeline-container
          image: 055745520549.dkr.ecr.us-east-1.amazonaws.com/app_pipeline
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: app-pipeline-service
spec:
  selector:
    app: app-pipeline
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
